<?php

namespace ServerGrove\KbBundle\Repository;

use Doctrine\ODM\PHPCR\DocumentRepository;
use Doctrine\ODM\PHPCR\Id\RepositoryIdInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository implements RepositoryIdInterface
{

    /**
     * @param $username
     *
     * @return \ServerGrove\KbBundle\Document\User
     */
    public function findOneByUsername($username)
    {
        return $this->find('/users/'.$username);
    }

    /**
     * @return array
     */
    public function getEditorsEmails()
    {
        $users = $this->getDocumentManager()->getRepository('ServerGroveKbBundle:User')->findBy(array(
            'roles' => 'ROLE_ADMIN' # Is it ok to use it this way?
        ));

        $emails = array();
        foreach ($users as $user) {
            $emails[] = $user->getEmail();
        }

        return $emails;
    }

    /**
     * Generate a document id
     *
     * @param object $document
     * @param object $parent
     *
     * @return string
     */
    public function generateId($document, $parent = null)
    {
        return '/users/'.$document->getUsername();
    }
}
